name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'Release Type(next, beta, alpha, latest)'
        required: true
        default: 'latest'
        options:
        - next
        - beta
        - alpha
        - latest
      branch:
        description: 'Release Branch(confirm release branch)'
        required: true
        default: 'main'

jobs:
  release:
    name: Release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'pnpm'

      - name: Install Dependencies && Build
        run: pnpm install

      - name: Release
        uses: web-infra-dev/actions@v2
        with:
          version: ${{ github.event.inputs.version }}
          branch: ${{ github.event.inputs.branch }}
          type: 'release'
          tools: 'modern'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}


